"""Weekly 'your reading week' + resurfaced-memory digest (B4.2, Tier 2).

A calm reason to return that isn't a streak. Generated by a scheduled job (an
admin/cron trigger calls run_weekly_digests). Idempotent per user per ISO week,
and deliberately silent when there's nothing worth saying — no empty guilt ping.
"""

import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.book_entry import BookEntry
from app.models.notification import NotificationDigest, TIER_DIGEST
from app.models.user import User
from app.services.insight_service import current_week_key, get_or_cache_weekly_memory
from app.services.notification_service import notify


async def _books_this_week(db: AsyncSession, user_id: uuid.UUID) -> int:
    since = datetime.now(timezone.utc) - timedelta(days=7)
    return (await db.execute(
        select(func.count(BookEntry.id)).where(
            BookEntry.user_id == user_id, BookEntry.created_at >= since
        )
    )).scalar() or 0


async def generate_weekly_digest_for_user(db: AsyncSession, user: User, period: str) -> bool:
    """Returns True if a digest notification was delivered to this user."""
    already = (await db.execute(
        select(NotificationDigest.id).where(
            NotificationDigest.user_id == user.id, NotificationDigest.period == period
        )
    )).scalar_one_or_none()
    if already is not None:
        return False

    books = await _books_this_week(db, user.id)
    memory, _ = await get_or_cache_weekly_memory(db, user)
    payload = {"period": period, "books_this_week": books, "memory": memory}

    # Mark the period processed regardless, so we don't recompute every run.
    db.add(NotificationDigest(user_id=user.id, period=period, payload=payload))

    if books == 0 and not memory:
        await db.flush()
        return False

    n = await notify(db, user.id, TIER_DIGEST, "weekly_digest", payload=payload)
    await db.flush()
    return n is not None


async def run_weekly_digests(db: AsyncSession) -> int:
    """Generate this week's digests for all users. Returns the number delivered."""
    period = current_week_key()
    users = list((await db.execute(select(User))).scalars().all())
    sent = 0
    for user in users:
        if await generate_weekly_digest_for_user(db, user, period):
            sent += 1
    return sent
